### ISSUE TITLE
Python 3 version is not working

### ISSUE THREAD

**Issue by DavidNemeskey** [juditacs/wordcount#4]
When executed with an UTF-8 locale, it outputs completely different counts than e.g. the py2 / java versions. When executed with the C locale, it fails at the output phase with
```
UnicodeEncodeError: 'ascii' codec can't encode character '\xee' in position 0: ordinal not in range(128)
```

**Comment by juditacs** [comment]
Thanks for the info.
I have trouble understanding Python3's utf8 handling.

Can you create a simple test case for detecting this?

**Comment by juditacs** [comment]
Locale is set automatically when using the provided Dockerfile, otherwise it should be set manually.
I'll add this to the README later.

**Comment by juditacs** [comment]
The Romanian corpus was full of invalid characters so I decided to replace it with a more standard corpus.
This issue is labelled as WONTFIX
