### ISSUE TITLE
Delete wordcount2.js

### ISSUE THREAD

**Issue by juditacs** [juditacs/wordcount#51]
@kundralaci @szelpe I would like to delete wordcount2.js, it's slower than wordcount.js. Is it ok?

**Comment by kundralaci** [comment]
I have just deleted it in my fork too, so it's absolutely okay for me.

**Comment by juditacs** [comment]
Done. https://github.com/juditacs/wordcount/commit/3120fec26941885dac2588e97d807043decb2ae9
