### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by kpeu3i** [juditacs/wordcount#87]
My pull request was merged [22 days ago (25.04.2016)](https://github.com/juditacs/wordcount/commit/bcdab5c9cbc9144caf99e7e336a4e1b82ea3cdab), but results (leaderboard) still not updated.

**Comment by juditacs** [comment]
It wasn't on top of my priority list, but I'll update it shortly.

**Comment by kpeu3i** [comment]
Ok, thanks!

**Comment by juditacs** [comment]
I reran everything and the results are very different on the new environment. I'll discuss with the others how to publish it, but here you go in the meantime:

| Rank | Experiment | CPU seconds | User time | Maximum memory | Contributor |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | cpp/wordcount_clang | 223.65 | 211.6 | 4904080 |  |
| 2 | cpp/wordcount | 230.84 | 212.66 | 4903864 | Dmitry Andreev, Matias Fontanini, Judit Acs |
| 3 | rust/wordcount/wordcount | 261.27 | 202.05 | 6927312 | Joshua Holmer |
| 4 | java -Xms2G -Xmx8G -classpath java:java/trove-3.0.3.jar WordCountOptimized | 294.99 | 326.12 | 4367540 |  |
| 5 | c/wordcount | 298.74 | 273.84 | 2441544 | gaebor |
| 6 | d/wordcount | 299.71 | 284.88 | 6341764 | Pavel Chebotarev |
| 7 | php7.0 php/wordcount.php | 301.75 | 264.79 | 4145904 | Andrey Bukatov, Braun Patrik |
| 8 | hhvm php/wordcount.php | 314.09 | 285.84 | 5043480 | Andrey Bukatov, Braun Patrik |
| 9 | python/wordcount_py2.py | 417.07 | 402.59 | 3937904 | Judit Acs |
| 10 | go/bin/wordcount | 448.82 | 434.29 | 5441988 | David Siklosi |
| 11 | mono csharp/WordCount.exe | 635.68 | 612.17 | 4518568 | Joe Amenta, Tim Posey, Peter Szel |
| 12 | python/wordcount_py2_baseline.py | 642.39 | 620.03 | 8871152 | Judit Acs |
| 13 | php5.6 php/wordcount.php | 676.54 | 647.68 | 12666260 | Andrey Bukatov, Braun Patrik |
| 14 | perl/wordcount.pl | 928.12 | 901.09 | 7163828 | Larion Garaczi, Judit Acs |
| 15 | java -Xms2G -Xmx8G -classpath java WordCountBaseline | 994.1 | 1175.36 | 7449504 |  |
| 16 | cpp/wordcount_baseline | 1104.92 | 996.88 | 6003768 | Judit Acs |
| 17 | python/wordcount_py3.py | 1198.97 | 1166.51 | 7729680 | Judit Acs |
| 18 | lua lua/wordcount.lua | 1323.48 | 1202.48 | 7165012 | daurnimator |
| 19 | julia julia/wordcount.jl | 1818.15 | 1777.7 | 7432000 | Attila Zseder, getzdan |
| 20 | scala -J-Xms2G -J-Xmx8g -classpath scala Wordcount | 2279.6 | 2434.17 | 7195004 |  |
| 21 | elixir/wordcount | 2434.46 | 2384.15 | 13111752 | Norbert Melzer |
| 22 | java -Xms2G -Xmx8G -cp clojure.jar clojure.main clojure/wordcount.clj | 3690.21 | 4142.74 | 8337532 | lverweijen |

**Comment by sgwerder** [comment]
What do you think was the cause for this difference in the new environment?

**Comment by juditacs** [comment]
My only guess is the available disk space which is running pretty low. I just started another test and I'll try to ask for more disk for the VM.

**Comment by svanoort** [comment]
@juditacs I'll curious to hear what comes out of the disk space discussion there.  We may have some other form of regression at play here (going from version 14.04 to version 16.06 is a pretty major OS upgrade too, especially with the changes in language versions & compilers).

**Comment by juditacs** [comment]
The difference was probably due to low disk space. My new tests are not that surprising, I'm updating right now.
